name: app_runner
description: Launch your Flutter app like a pro! AppRunner is a configurator for quick and controlled launch of your application.
version: 2.2.0+1
repository: https://github.com/MadBrains/App-Runner-Flutter
issue_tracker: https://github.com/MadBrains/App-Runner-Flutter/issues
homepage: https://madbrains.ru/
dev_line_length: 120

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: